language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: integration test
      script:
        - docker run -d -p 5672:5672 -p 15672:15672 --name messenger-demo-rabbit rabbitmq:3
        - ./gradlew testInteg
    - stage: docker hub push
      if: branch = master
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - ./gradlew dockerPush
