language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: integration test
      script:
        - docker run --name messenger-demo-redis -p 6379:6379 -d redis
        - ./gradlew testInteg
    - stage: docker hub push
      if: branch = master
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - ./gradlew dockerPush
