version: "3.1"

services:

  server:
    image: attilapapai/messenger-demo
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8080:8080
    networks:
      - messengernet

  db:
    image: postgres
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: messenger
    networks:
      - messengernet

  rabbitmq:
    image: rabbitmq:management
    networks:
      - messengernet

networks:
  messengernet:

